# Generated by Django 5.0.1 on 2024-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="previous_price",
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6),
            preserve_default=False,
        ),
    ]
