# Generated by Django 5.0.1 on 2024-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_product_name_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(to="home.color"),
        ),
    ]
