# Generated by Django 5.0.1 on 2024-01-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_color_remove_product_colors_product_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.AddField(
            model_name="color",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.product",
            ),
        ),
    ]
