# Generated by Django 5.0.1 on 2024-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_product_colors_color_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="color",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(to="home.color"),
        ),
    ]
