# Generated by Django 5.0.1 on 2024-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_color_product_product_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color",
            field=models.CharField(default="Brown", max_length=100),
            preserve_default=False,
        ),
    ]
